### ISSUE TITLE
The question of this tools used in plant parasites nematode?

### ISSUE THREAD

**Issue by hzaumsq** [JanaSperschneider/EffectorP-2.0#1]
Dear author;
Did this tools fit to finding the effector in plant parasites nematode,If I want to use this tools to do something like you,need I to change the practice data when I want to trian the model ?

**Comment by JanaSperschneider** [comment]
Hi there and apologies for the very late reply, I only just saw your question.

EffectorP has been trained on fungal effectors, so it will only work for nematode effectors if they share common properties. I think it is unlikely, as nematodes deliver effectors to their host in other ways than fungi. If you want to train a machine learning model to predict nematode effectors, yes you will need to use different training data (i.e. nematode effectors and secreted nematode non-effectors) and create a WEKA machine learning model. You could then recycle the rest of the EffectorP code to predict nematode effectors with your own model.

Hope this answers your question, thanks!
Jana
