### ISSUE TITLE
Output formats

### ISSUE THREAD

**Issue by Caro-Ca** [JanaSperschneider/EffectorP-2.0#2]
Hi all, 
I am reading this section `http://effectorp.csiro.au/output.html` in which says that EffectorP can retrieve a FASTA file and a summary table. I understand this option is if I use the website, but how can I get those output formats for Linux? 

Thanks for your help

**Comment by JanaSperschneider** [comment]
Hi there,

it should work as follows:

python EffectorP.py -s -o <output_table> -E <effectors.fasta> -i <input_file>

where basic options are:
-h : show brief help on version and usage
-s : short output format that provides predictions for all proteins as one tab-delimited table [default long format]
-o <f> : direct output to file <f>, not stdout
-E <f> : save predicted effectors to FASTA file <f>       
-N <f> : save predicted non-effectors to FASTA file <f>

**Comment by Caro-Ca** [comment]
Amazing! Thank you
