### ISSUE TITLE
EffectorP pepstats issue

### ISSUE THREAD

**Issue by tayabsoomro** [JanaSperschneider/EffectorP-2.0#3]
I am running EffectorP and I get the following issue with both Effector_Testing.fa and my protein file.

`Call pepstats...
/../software/EffectorP_2.0/Scripts/EMBOSS-6.5.7/emboss/.libs/lt-pepstats: symbol lookup error: /../software/EffectorP_2.0/Scripts/EMBOSS-6.5.7/emboss/.libs/lt-pepstats: undefined symbol: embIeppKDel
Error calling pepstats: Calling pepstats returned 127`

Any suggestions?

**Comment by tayabsoomro** [comment]
I tried it with EffectorP 1.0 with same behaviour. I am following the instructions for installing EMBOSS exactly as they are written.

**Comment by JanaSperschneider** [comment]
Hi there, to me this looks like an installation/compilation issue with EMBOSS. Can you execute the ./configure followed by make and observe if you see any error messages during the compilation?

**Comment by tayabsoomro** [comment]
You seem to be right. When I did `./configure --without-x`, it threw that pepstats error. With X11, it doesn't seem to throw that error.

Would it be possible to use this tool without X11?

**Comment by JanaSperschneider** [comment]
Yes, I believe so. Can you try and let me know how you go?
Thanks!

**Comment by tayabsoomro** [comment]
Alright, so I checked and the `--without-x` option seems to work just fine on another server. I believe there was something wrong during `./configure` step when I first ran it.
