### ISSUE TITLE
Updating to python3

### ISSUE THREAD

**Issue by darcyabjones** [JanaSperschneider/EffectorP-2.0#4]
Hi Jana,

I'm sure you're aware that python2 is no longer maintained.
Do you mind if I submit pull requests to update your tools to use python3?

If you'd prefer, I can make it backwards compatible with python2 using the [future](https://pypi.org/project/future/) module, but several operating systems and tools like pip have indicated that they'll be dropping support for python2 in the near future.

Thanks.
Hope it's going well over in Canberra :)

Darcy

**Comment by JanaSperschneider** [comment]
Hi Darcy,

sure put in a pull request. I suspect it is mostly the print statements that need to be changed for Python 3, or did you spot any other issues?

Cheers,
Jana

**Comment by darcyabjones** [comment]
Hi Jana,

Yes It was mostly just print statements, but there were also a few exceptions and `xrange` calls that had to be changed too.

Will submit them now :)

**Comment by darcyabjones** [comment]
Submitted PR #5
